name: ZFSBootMenu
on: [ push ] 

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master

  build:
    name: Build boot images 
    runs-on: ubuntu-latest 
    container:
      image: ghcr.io/zbm-dev/zbm-builder
    steps:
      - uses: actions/checkout@master

      - name: Create files
        run: |
          ln -s "$(pwd)" /zbm
          ls -lah /zbm
           [ -x /zbm/releng/docker/zbm-build.sh ] && /zbm/releng/docker/zbm-build.sh

      - name: Archive EFI 
        uses: actions/upload-artifact@v2
        with:
          name: EFI 
          path: /zbm/contrib/docker/build/*.EFI

      - name: Archive components 
        uses: actions/upload-artifact@v2
        with:
          name: Components 
          path: |
            /zbm/contrib/docker/build/*
            !/zbm/contrib/docker/build/*.EFI
